version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tododb
      DB_USER: devops
      DB_PASSWORD: devops
    ports:
      - "4000:4000"
    command: ["node", "src/index.js"]

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    # NO necesita volumes ni command
    # porque ya sirves con NGINX

volumes:
  pgdata:
