services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./todo-backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=todoapp
      - DB_PORT=5432
    depends_on:
      - postgres

  frontend:
    build: ./todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
