global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']  # Cambia aquí si expones métricas desde backend

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']  # Si usas un exporter de Postgres
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']    