stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build || echo "No build script"
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  image: node:18
  script:
    - npm install
    - npm test || echo "No tests"

deploy:
  stage: deploy
  script:
    - echo "Deploy stage placeholder"
